// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import StoreProvider from "./StoreProvider";
// import { Toaster } from "@/components/ui/sonner";
// import { TooltipProvider } from "@/components/ui/tooltip";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <StoreProvider>
//        <TooltipProvider>
//          <body className="min-h-full flex flex-col">
//           {children}
//           <Toaster   position="top-center" 
//               richColors 
//               closeButton 
//               duration={3000} />

//         </body>
//        </TooltipProvider>
//       </StoreProvider>

//     </html>
//   );
// }



// src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
    title: "Create Account",
    description: "Register a new account",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <StoreProvider>
                    {children}
                    <Toaster
                        position="top-center"
                        richColors
                        closeButton
                        duration={3000}
                    />
                </StoreProvider>
            </body>
        </html>
    );
}